; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60315.1 

	;	D:\Asmbook 7\examples\ch08\32 bit\C_Examples\C_Examples\makeArray.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_makeArray
PUBLIC	_main
EXTRN	@__security_check_cookie@4:PROC
EXTRN	___security_cookie:DWORD
; Function compile flags: /Ogtp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT
; File d:\asmbook 7\examples\ch08\32 bit\c_examples\c_examples\makearray.c
; Line 20
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT _makeArray
_TEXT	SEGMENT
__$ArrayPad$ = -4					; size = 4
_makeArray PROC						; COMDAT
; File d:\asmbook 7\examples\ch08\32 bit\c_examples\c_examples\makearray.c
; Line 4
	push	ebp
	mov	ebp, esp
	sub	esp, 36					; 00000024H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
; Line 8
	xor	eax, eax
$LL3@makeArray:
	inc	eax
	cmp	eax, 30					; 0000001eH
	jl	SHORT $LL3@makeArray
; Line 11
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
_makeArray ENDP
_TEXT	ENDS
END
